package com.cosme.backend.model;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// Ticket.java (entity). Look up @Entity, @Id, @GeneratedValue, and Lombok's @Data / @NoArgsConstructor.

@Entity 
@NoArgsConstructor 
@Getter 
public class Ticket {
  @Id 
  @GeneratedValue (strategy = GenerationType.IDENTITY)
  private Long id;

  @Setter private int tableNumber;

  @Setter private String items;

  @Column(precision = 10, scale = 2)
  @Setter private BigDecimal total;
  
  @Setter private boolean paid;

  // All args constructor except id which is autogenerated
  public Ticket(int tableNumber, String items, BigDecimal total, boolean paid) {
    this.tableNumber = tableNumber;
    this.items = items;
    this.total = total;
    this.paid = paid;
  }
}
